# Welcome to Jekyll Vanta!
title: Jekyll Vanta
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: 
plugins:
  - jekyll-feed

# Vanta Settings 

vanta: true       # Enable vanta background 
vanta-theme: wave       # options: globe, net, dots, wave


# Home Settings 

home-type: landing      # options: landing, features,what do you want on the home page?

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
